name: Build & deploy

on:
   push:
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout Code
           uses: actions/checkout@v3

         - name: Set up PHP
           uses: shivammathur/setup-php@v2
           with:
             php-version: '8.0.30' # Adjust the PHP version as needed
             extensions: mbstring, intl, curl
             tools: composer

         - name: Install Composer Dependencies
           run: composer install --no-dev --optimize-autoloader
      
         - name: Deploy
           uses: easingthemes/ssh-deploy@v2.2.11
           env:
              SSH_PRIVATE_KEY: ${{ secrets.DEPLOYUSER_SSH_KEY }}
              REMOTE_HOST: ${{ secrets.DEPLOYUSER_HOST }}
              REMOTE_USER: ${{ secrets.DEPLOYUSER_USER }}
              REMOTE_PORT: ${{ secrets.DEPLOYUSER_PORT }}
              TARGET: "/srv/www/www.asteriski.fi/wp-content/plugins/wp-asteriski-calendar/"
              EXCLUDE: "/.git/"
           with:
             args: "-avz --delete --chmod=ug=rwx,o=rx --chown=github-deploy:www-data --progress"
